import './app/Unacademic.spec.js';
import './main/Main.spec.js';
import './sidebar/index.spec.js';
import './contentPanel/index.spec.js';
import './cards/index.spec.js';
import './editable/Editable.spec.js';
import './viewer/Viewer.spec.js';
import './sliders/SliderSection.spec.js';
import './sliders/Slider.spec.js';
